export enum FailureType {
    NONE = "NONE",
    LOCATOR = "LOCATOR",
    ASSERTION = "ASSERTION",
    TIMEOUT = "TIMEOUT",
    NAVIGATION = "NAVIGATION",
    NETWORK = "NETWORK",
    API = "API",
    AUTHENTICATION = "AUTHENTICATION",
    TEST_DATA = "TEST_DATA",
    ENVIRONMENT = "ENVIRONMENT",
    BROWSER = "BROWSER",
    UNKNOWN = "UNKNOWN"
}